# Generated by Django 4.0.4 on 2022-05-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('img', models.CharField(max_length=1000)),
                ('director', models.CharField(max_length=250)),
                ('cast', models.CharField(max_length=1000)),
                ('book', models.CharField(max_length=1000)),
                ('movie', models.CharField(max_length=1000)),
                ('list', models.ManyToManyField(to='main_app.list')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('img', models.CharField(max_length=1000)),
                ('cast', models.CharField(max_length=1000)),
                ('trailer', models.CharField(max_length=1000)),
                ('book', models.CharField(max_length=1000)),
                ('plays', models.CharField(max_length=1000)),
                ('list', models.ManyToManyField(to='main_app.list')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('img', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=250)),
                ('preview', models.CharField(max_length=1000)),
                ('list', models.ManyToManyField(to='main_app.list')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
