# Generated by Django 4.0.4 on 2022-05-07 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='book',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='plays',
        ),
        migrations.RemoveField(
            model_name='play',
            name='book',
        ),
        migrations.RemoveField(
            model_name='play',
            name='movie',
        ),
        migrations.AddField(
            model_name='book',
            name='movies',
            field=models.ManyToManyField(to='main_app.movie'),
        ),
        migrations.AddField(
            model_name='book',
            name='plays',
            field=models.ManyToManyField(to='main_app.play'),
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
