# Generated by Django 4.0.4 on 2022-05-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_book_list_remove_movie_list_remove_play_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='movies',
            field=models.ManyToManyField(default='none', null=True, to='main_app.movie'),
        ),
        migrations.AlterField(
            model_name='book',
            name='plays',
            field=models.ManyToManyField(default='none', null=True, to='main_app.play'),
        ),
    ]
