# Generated by Django 4.0.4 on 2022-05-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_book_movies_alter_book_plays'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='movies',
            field=models.ManyToManyField(blank=True, to='main_app.movie'),
        ),
        migrations.AlterField(
            model_name='book',
            name='movies',
            field=models.ManyToManyField(to='main_app.movie'),
        ),
        migrations.AlterField(
            model_name='book',
            name='plays',
            field=models.ManyToManyField(to='main_app.play'),
        ),
    ]
