# Generated by Django 4.0.4 on 2022-05-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_play_movies_alter_book_movies_alter_book_plays'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='books',
            field=models.ManyToManyField(to='main_app.book'),
        ),
        migrations.AddField(
            model_name='list',
            name='movies',
            field=models.ManyToManyField(to='main_app.movie'),
        ),
        migrations.AddField(
            model_name='list',
            name='plays',
            field=models.ManyToManyField(to='main_app.play'),
        ),
    ]
