# Generated by Django 4.0.4 on 2022-05-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_list_books_list_movies_list_plays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='books',
            field=models.ManyToManyField(blank=True, to='main_app.book'),
        ),
        migrations.AlterField(
            model_name='list',
            name='movies',
            field=models.ManyToManyField(blank=True, to='main_app.movie'),
        ),
        migrations.AlterField(
            model_name='list',
            name='plays',
            field=models.ManyToManyField(blank=True, to='main_app.play'),
        ),
    ]
