# Generated by Django 4.0.4 on 2022-05-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_list_books_alter_list_movies_alter_list_plays'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='preview',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='play',
            name='preview',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='movies',
            field=models.ManyToManyField(blank=True, to='main_app.movie'),
        ),
        migrations.AlterField(
            model_name='book',
            name='plays',
            field=models.ManyToManyField(blank=True, to='main_app.play'),
        ),
    ]
