# Generated by Django 4.0.4 on 2022-05-13 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_book_movies_alter_book_plays'),
        ('main_app', '0008_movie_preview_play_preview_alter_book_movies_and_more'),
    ]

    operations = [
    ]
